### ISSUE TITLE
Not working with latest mongodb

### ISSUE THREAD

**Issue by imaia** [REMnux/docker#13]
Well, using the latest mongodb version, crits server won't start. Not quite sure why. Had to fallback to the latest mongodb from ubuntu repository.

**Comment by lennyzeltser** [comment]
Is this still an issue?

**Comment by prajwalyashasvi** [comment]
@lennyzeltser i get ERROR: child process failed, exited with error number 100, when trying to run. 
do i need to have data in local system to test run the docker?

**Comment by wzod** [comment]
I'll take a look into the issue and should have a resolution by end of week (Friday). I'm currently setting up my environment to test on Ubuntu 16.04 to ensure consistency with recent changes.

Thanks for posting the issue!

**Comment by prajwalyashasvi** [comment]
Yeah Sure thanks for the reply.. I didn't get to try it again at home I'll
update you if it works, i Was trying from workplace.

**Comment by wzod** [comment]
Submitted pull request (#17) that resolves the issues that were introduced when using a newer version of mongodb that is not supported by the CRITs project.

I have pushed the updated Dockerfile to my public repo ( wzod/crits ). If no issues, the REMnux repo will need a similar push to the remnux/crits repo.

If any questions, please let me know.

Hope this helps!

**Comment by lennyzeltser** [comment]
I updated the Dockerfile to include @wzod's fixes. Thanks!

**Comment by prajwalyashasvi** [comment]
Thanks @wzod and Lenny will try it again in a few days.
