### ISSUE TITLE
ruby not installed

### ISSUE THREAD

**Issue by lengers** [REMnux/docker#16]
Since the latest pull, ruby and rvm are no longer present in the container. Therefore, executing msfconsole or other tools does not work, which renders the container useless.

**Comment by lennyzeltser** [comment]
@lengers, is this no longer a problem?

**Comment by lengers** [comment]
Apparently, I was really stupid. I executed a shell on the docker container and neither the commands 'ruby' nor 'msfconsole' worked. Using docker attach, everything works fine.
