### ISSUE TITLE
Issue on remnux/metasploit

### ISSUE THREAD

**Issue by nov3mb3r** [REMnux/docker#19]
Every time the container is opened, it has to forego re-installation because ruby is missing

**Comment by Nasjoe** [comment]
Can you tell us wich command you have to launch ?
Thx !

**Comment by nmantas** [comment]
'sudo  docker run --rm -it -p 443:443 -v ~/.msf4:/root/.msf4 -v /tmp/msf:/tmp/data remnux/metasploit'

**Comment by ilatypov** [comment]
rapid7/metasploit now includes own Dockerfile and the docker image builder/runner in docker/bin/msfconsole.  It gets a lighweight Linux distribution with the appropriate version of ruby and installs itself into it.  It runs PostgreSQL in a separate container co-ordinated with the client using docker-compose.

**Comment by lennyzeltser** [comment]
Thanks for the pointer, @ilatypov
