### ISSUE TITLE
Need help with thug shared log folder perms

### ISSUE THREAD

**Issue by adricnet** [REMnux/docker#2]
Using the invocation from the [docs](https://remnux.org/docs/containers/run-apps/#thug-low-interaction-honeyclient-remnuxthug), thug works great, but I'm having trouble when I try to share a folder into it. It errors out on permissions.. sometimes. EG:

    $ docker run --rm -it -v ~/Desktop/mess/thuglogs:/home/thug/logs remnux/thug ./thug.py 'http://google.com'

    Traceback (most recent call last):
     File "./thug.py", line 242, in <module>
    Thug(sys.argv[1:])()
     File "/home/thug/src/ThugAPI/ThugAPI.py", line 63, in __call__
    self.analyze()
    File "./thug.py", line 221, in analyze
    self.log_init(args[0])
    File "/home/thug/src/ThugAPI/ThugAPI.py", line 185, in log_init
    log.ThugLogging.set_basedir(url)
    File "/home/thug/src/Logging/BaseLogging.py", line 59, in set_basedir
    os.makedirs(self.baseDir)
    File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '../logs/4be8c7ad7ca1a9ecd27ab96956468ca8/20150108173240'

Maybe it is creating a folder that the next thug Docker instance can't access unless perms in/of the shared *thuglogs* folder are reset between invocations. This has helped between invocations, but I don't understand what's causing it:

    $ chmod -R o+rwx thuglogs/

By running bash rather than thug in a thug container to take a peek we can see the user id mapping is off but the perms look okay:

    thug@8c7d174f26e9:~/src$ ls -ld ~/logs/
    drwxrwxrwx 1 1000 staff 272 Jan  8 17:32 /home/thug/logs/
    
    lorelei:mess adric$ ls -ld thuglogs
    drwxrwxrwx  8 adric  staff  272 Jan  8 12:32 thuglogs

but a run of thug also fails similarly as above (trimmed):

    OSError: [Errno 13] Permission denied: '../logs/67ef91b090ead0b6426960bc5f7cc059/20150108175411'

This folder and all of them are there, but empty.

    thug@38edce58f9bc:~/src$ ls -a ~/logs/*/
    /home/thug/logs/4be8c7ad7ca1a9ecd27ab96956468ca8/:
    .  ..

    /home/thug/logs/67ef91b090ead0b6426960bc5f7cc059/:
    .  ..

    /home/thug/logs/873c87c71f8bf1d15a53ce0c0676971f/:
    .  ..

    /home/thug/logs/c02b57cf40deb5dd86bf434fc7d4f68f/:
    .  ..

    /home/thug/logs/c0fd94d2694ae2ac06f5abe87a987b5d/:
    .  ..

    /home/thug/logs/c7b920f57e553df2bb68272f61570210/:
    .  ..

Please help, thanks,
adric

**Comment by adricnet** [comment]
Works fine on a fresh LTS 14 VM. Although the user ID mapping is wonky the perms and logs folder share work. Closing this one as it may be a Mac  or Docker bug. Thanks!

**Comment by lennyzeltser** [comment]
Thanks for reporting and looking into this. As long as you make the shared folder world-accessible, access should be granted without any issues. Glad it worked on a fresh Ubuntu system.
