### ISSUE TITLE
Add public builds

### ISSUE THREAD

**Issue by lazzurs** [REMnux/docker#31]
It is not clear where the current builds of these containers are being done.

Given these are security tools it would be great to see the builds happening in a public build system to increase trust in built Docker containers. TravisCI, CircleCI or the Docker Hub build system would be great.

Happy to help on getting the builds into any of those or any other public build system.

**Comment by lennyzeltser** [comment]
Hi, @lazzurs. The builds are currently being done [on Docker Hub](https://hub.docker.com/u/remnux/), which uses this Github repository on Github as the source of its Dockerfiles. I'll adjust the README file on Github to mention this--thanks for letting me know that it's unclear.
