### ISSUE TITLE
dockerfile config changes

### ISSUE THREAD

**Issue by Srinivasa381224** [REMnux/docker#44]
Hi, am srinivasa working as a devops engineer am created simple docker file for my application i need to change some configuration of that application through dockerfile is there any way to change after war file is generated help me for this

**Comment by lennyzeltser** [comment]
This question seems unrelated to REMnux, and is probably more appropriate for a general Docker forum. If you are reporting a matter related to the Dockerfiles supplied as part of the REMnux project, please reopen the issue and share additional details to clarify.
