### ISSUE TITLE
[Thug] code.google.com no longer supporting svn

### ISSUE THREAD

**Issue by kevthehermit** [REMnux/docker#9]
Also raised this on the official Thug repo

This is taken from the Google Code website https://code.google.com/p/support/wiki/ReadOnlyTransition

```
After January 2016 you will no longer be able to access source code from a version control client; however project data will still be available from the Google Code Archive.
```

I know that V8 has officially moved to https://github.com/v8/v8
but i cant find a new 'Official' pyv8

**Comment by lennyzeltser** [comment]
I think the official pyv8 build is in the following repository: https://github.com/flier/pyv8. However, I don't believe the project is being actively maintained.

**Comment by kevthehermit** [comment]
The issue still stands!

In January the current Docker file will fail when it tries to svn to google code. 

Even if you switch to the https://github.com/flier/pyv8 repo.

The pyv8 setup.py has hard coded subversion calls and checks to:

http://v8.googlecode.com/svn/trunk/
http://pyv8.googlecode.com/svn/trunk/
http://gyp.googlecode.com/svn/trunk build/gyp

All of which will fail when googlecode stops accepting connections from svn

**Comment by kevthehermit** [comment]
Same applies to the v8 and pescanner docker images, that have hardcoded google code urls

**Comment by lennyzeltser** [comment]
Good points. The biggest challenge is that pyv8 seems to no longer have an active maintainer. Perhaps a community member will find the time to mirror pyv8 and change references to Google Code to address the problem in the short term.

**Comment by kevthehermit** [comment]
I raised the same issue with Angelo on Thugs repo. He has cloned the pyv8 repo and is actively looking at replacing pyv8 in the near future as it is no longer maintained. 

https://github.com/buffer/thug/issues/143

**Comment by kevthehermit** [comment]
Took longer than the origional announcment but You can no longer svn to google code so this can no longer be built. Thugs main repo has a patched pyv8 that bypasses the svn calls.

**Comment by lennyzeltser** [comment]
I updated the "remnux/thug" image to install the latest version of Thug and use Angelo's cloned pyv8 repository.
